"""ForgeKits — Layer 3: file writer.

Takes GeneratedFile objects and writes them to disk.
Also generates DECISIONS.md from accumulated decisions.
"""

from __future__ import annotations

from pathlib import Path

from forgekits.models import GeneratedFile, PhaseEnvelope


class ProjectWriter:
    """Writes generated files to disk."""

    def __init__(self, output_dir: Path) -> None:
        self._output_dir = output_dir

    def write_all(self, files: list[GeneratedFile]) -> int:
        """Write all generated files. Returns count of files written."""
        self._output_dir.mkdir(parents=True, exist_ok=True)
        count = 0

        for gf in files:
            file_path = self._output_dir / gf.path
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(gf.content, encoding="utf-8")
            count += 1

        return count

    def write_decisions(
        self, decisions: list[str], envelopes: list[PhaseEnvelope]
    ) -> None:
        """Generate and write DECISIONS.md from accumulated decisions."""
        lines = [
            "# Architecture Decisions",
            "",
            "> Auto-generated by ForgeKits. This documents *why* the code is structured",
            "> the way it is — so you can understand and extend it confidently.",
            "",
        ]

        # Group decisions by phase
        for envelope in envelopes:
            lines.append(f"## {envelope.phase_name.replace('_', ' ').title()}")
            lines.append("")
            if envelope.key_decisions:
                for decision in envelope.key_decisions:
                    lines.append(f"- {decision}")
                lines.append("")
            if envelope.constraints:
                lines.append("**Constraints established:**")
                for constraint in envelope.constraints:
                    lines.append(f"- {constraint}")
                lines.append("")

        # Add any standalone decisions not tied to envelopes
        standalone = [d for d in decisions if not any(
            d in env.key_decisions for env in envelopes
        )]
        if standalone:
            lines.append("## Additional Decisions")
            lines.append("")
            for d in standalone:
                lines.append(f"- {d}")
            lines.append("")

        decisions_path = self._output_dir / "DECISIONS.md"
        decisions_path.write_text("\n".join(lines), encoding="utf-8")
